name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: transaction
          MYSQL_USER: transaction
          MYSQL_PASSWORD: transaction
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo_mysql, zip
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy .env file
        run: cp .env.example .env

      - name: Set DB_HOST for CI
        run: echo "DB_HOST=mysql" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Clear cache
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run Feature and Unit Tests
        run: php artisan test

      - name: Run PHPStan (Static Analysis)
        run: ./vendor/bin/phpstan analyse --no-progress --level=max app

      - name: Run PHPMD (Code Mess Detection)
        run: ./vendor/bin/phpmd app text cleancode,codesize,design,naming,unusedcode

      - name: Run PHP-CS-Fixer (Dry Run)
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
